#! /usr/bin/python

# Define a dictionary with the following key:value pairs
# sheet_name:[field_1, ..., field_n], which is used to
# check that each sheet is structured correctly

sheet_field_dict = {	'2018 TLS-TL0 enrols':		['Comment',
													'Teaching Period',
													'Course Admin Team',
													'Student ID',
													'Unit Funding Source',
													'Course Code',
													'Fee Category',
													'Unit Code',
													'Override Activity Start Date',
													'Course Commencement Date'],
							
							'Act End Dt Error':		['Comment',
													'Course Admin Team',
													'Student ID',
													'Student First Name',
													'Student Last Name',
													'Course Code',
													'Unit Code',
													'Teaching Period',
													'Grade',
													'Enrolment Activity End Date',
													'Cancelled Date',
													'Granted Date',
													'Result Date',
													'Disc Date',
													'Unit Census Date'],

							'Act St Dt Error':		['Comment',
													'Course Admin Team',
													'Student ID',
													'Course Code',
													'Unit Code',
													'Teaching Period',
													'Enrol Date',
													'Override Activity Start Date',
													'Unit Census Date'],

							'dup students':			['Comment',
													'Error_Msg',
													'Student ID',
													'Student First Name',
													'Student Last Name',
													'DOB',
													'Student Gender',
													'ATSI',
													'Disability Flag',
													'Residential Postcode',
													'COUNTRY OF BIRTH',
													'LANGUAGE',
													'Highest School Level Completed Year',
													'Highest School Level Completed'],

							'2017-18 student dups':	['Comment',
													'Error_Msg',
													'2018_Student_ID',
													'2018_Student_First_Name',
													'2018_Student_Last_Name',
													'2018_DOB',
													'2017_Student_ID',
													'2017_Student_First_Name',
													'2017_Student_Last_Name',
													'2017_DOB'],

							'VFH Errors':			['Comment',
													'Error Type',
													'Course Admin Team',
													'Teaching Period',
													'Student ID',
													'Course Code',
													'Unit Code',
													'Unit Delivery Location',
													'unit delivery Remoteness',
													'Unit Funding Source',
													'Fee Category',
													'Grade',
													'Administrative Unit Status',
													'CHESSN',
													'VET Stats ATSI',
													'VFH ATSI Code',
													'VFH Citizenship Code',
													'VFH Birth Country Code',
													'VFH Home Language Code',
													'VFH Term Location Postcode',
													'VFH Term Location Country Code',
													'VFH Home Location Postcode',
													'VFH Home Location Country Code',
													'VFH Arrival Year',
													'VFH Permanent Resident Code',
													'VFH Commencing Location Postcode',
													'VFH Commencing Geographic Location',
													'VFH Highest Attainment Code',
													'VFH Highest Attainment Year',
													'Basis For Admission Code',
													'HECS Payment Option Code',
													'Unit Student Status Code',
													'Enrol Date',
													'Unit Census Date'],

							'2017 enr, 2018 comp':	['Comment',
													'2018 Delivery Location Team',
													'Student ID',
													'Student First Name',
													'Student Last Name',
													'2017 Course Code',
													'WEEKLY_2017_Unit Code',
													'2017 Grade',
													'2017 Result Date',
													'WEEKLY_2017_Unit Funding Source',
													'2018 Course Code',
													'WEEKLY_CURRENT_Unit Code',
													'2018 Grade',
													'2018 Result Date',
													'WEEKLY_CURRENT_UNIT Funding Source'],

							'General Errors':		['Comment',
													'Error Type',
													'Course Admin Team',
													'Delivery Location Team',
													'Teaching Period',
													'Student ID',
													'Student Last Name',
													'Student First Name',
													'ATSI',
													'Gender',
													'DOB',
													'Deceased Indicator',
													'Disability',
													'Home Language Code',
													'Birth Country Code',
													'Residential Post Code',
													'Home State',
													'Prior Education',
													'Employment Category',
													'At School Indicator',
													'VET in School Indicator',
													'Highest School Level Completed Code',
													'Highest School Level Completed Year',
													'Age Highest School Completed',
													'Course Code',
													'Unit Code',
													'Unit Funding Source',
													'Enrol Date',
													'Outcome',
													'Unit Attempt Status',
													'Study Reason',
													'Intention to Complete Course',
													'Intention to Complete Unit/s Only',
													'No Course Intention',
													'Total LRNSUPP AHC',
													'Total Enrolled AHC (exc CT, SW, NS, LRNSUPP)',
													'Granted Date',
													'Cancelled Date',
													'Not Approved Date',
													'USI Flag',
													'Entitlement Contract Description',
													'Course Commencement Date',
													'Course Attempt Status'],

							'Course intent errors':	['Comment',
													'Error Type',
													'Course Admin Team',
													'Delivery Location Team',
													'Teaching Period',
													'Student ID',
													'Student Last Name',
													'Student First Name',
													'ATSI',
													'Gender',
													'DOB',
													'Deceased Indicator',
													'Disability',
													'Home Language Code',
													'Birth Country Code',
													'Residential Post Code',
													'Home State',
													'Prior Education',
													'Employment Category',
													'At School Indicator',
													'VET in School Indicator',
													'Highest School Level Completed Code',
													'Highest School Level Completed Year',
													'Age Highest School Completed',
													'Course Code',
													'Unit Code',
													'Unit Funding Source',
													'Enrol Date',
													'Outcome',
													'Unit Attempt Status',
													'Study Reason',
													'Intention to Complete Course',
													'Intention to Complete Unit/s Only',
													'No Course Intention',
													'Total LRNSUPP AHC',
													'Total Enrolled AHC (exc CT, SW, NS, LRNSUPP)',
													'Granted Date',
													'Cancelled Date',
													'Not Approved Date',
													'USI Flag',
													'Entitlement Contract Description',
													'Course Commencement Date',
													'Course Attempt Status'],

							'Inconsis fee&fund scr-pls chk':	['Comment',
																'Teaching Period',
																'Delivery Location Team',
																'Unit Delivery Location',
																'Remoteness',
																'Student ID',
																'VET School Name',
																'Course Code',
																'Unit Funding Source',
																'Fee Category',
																'Correspondence Category',
																'VET in School Indicator',
																'At School Indicator',
																'Staff Indicator',
																'Postal Postcode',
																'Student Home State'],

							'Duplicate SUA':		['Comment',
													'Delivery Location Team',
													'Student ID',
													'Unit Code',
													'Unit Attempt Status',
													'Teaching Period',
													'Grade',
													'Enrol Date',
													'Override Activity Start Date',
													'Result Date',
													'Enrolment Activity End Date',
													'Course Code',
													'Unit Funding Source',
													'Start Date',
													'End Date'],

							'superseded unit':		['Comment',
													'Course Admin Team',
													'Student ID',
													'Unit Code',
													'RELATED UNIT',
													'Course Code',
													'Override Activity Start Date',
													'Result Date',
													'Override Activity End Date',
													'Grade',
													'Teaching Period',
													'UNIT CODE DESCRIPTION'],

							'VFH-W chk for participation':	['Comment',
															'Delivery Location Team',
															'Student ID',
															'Student first Name',
															'Student Last Name',
															'Course Code',
															'Course Name',
															'Unit Code',
															'Teaching Period',
															'Grade',
															'Unit Delivery Location',
															'Enrol Date',
															'enrolment Activity End Date',
															'Disc Date']							

						}

sheet_field_dict_margaret = {	'TCI-not J':	['Comment',
												'Delivery Location Team',
												'Student ID',
												'Course Code',
												'Fee Category',
												'Unit Funding Source',
												'ACI',
												'TCI'],

								'K Missing TCI':['Comment',
												'Delivery Location Team',
												'Student ID',
												'Course Code',
												'Course Attempt Status',
												'Fee Category',
												'Unit Funding Source',
												'CURRENT TCI',
												'CURRENT ACI',
												'PREVIOUS TCI CODE',
												'PREVIOUS TCI START DTE',
												'PREVIOUS TCI END DTE'],

								'Fee and fund incon-pls chk':[	'Comment',
																'Teaching Period',
																'Delivery Location Team',
																'Unit Delivery Location',
																'Remoteness',
																'Student ID',
																'VET School Name',
																'Course Code',
																'Unit Funding Source',
																'Fee Category',
																'Correspondence Category',
																'VET in School Indicator',
																'At School Indicator',
																'Staff Indicator',
																'Postal Postcode',
																'Student Home State']
	
							}